"""empty message

Revision ID: 32b8786df106
Revises: ba86cc3b5caf
Create Date: 2024-11-02 00:45:24.565211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32b8786df106'
down_revision = 'ba86cc3b5caf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.drop_constraint('exercises_exercise_base_key', type_='unique')
        batch_op.drop_constraint('exercises_muscle_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.create_unique_constraint('exercises_muscle_key', ['muscle'])
        batch_op.create_unique_constraint('exercises_exercise_base_key', ['exercise_base'])

    # ### end Alembic commands ###
