"""empty message

Revision ID: ba86cc3b5caf
Revises: 3ff55f1434b5
Create Date: 2024-11-02 00:10:58.877705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba86cc3b5caf'
down_revision = '3ff55f1434b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('muscles', schema=None) as batch_op:
        batch_op.drop_constraint('muscles_name_en_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('muscles', schema=None) as batch_op:
        batch_op.create_unique_constraint('muscles_name_en_key', ['name_en'])

    # ### end Alembic commands ###
