"""Se agrego nuevo modelo SessionExerciseSeries

Revision ID: c05936d784f3
Revises: 4ed5ffa0b707
Create Date: 2024-11-15 03:17:26.581314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c05936d784f3'
down_revision = '4ed5ffa0b707'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session_exercise_series',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_exercise_id', sa.Integer(), nullable=False),
    sa.Column('series_number', sa.Integer(), nullable=False),
    sa.Column('repetitions_completed', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['session_exercise_id'], ['session_exercises.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('session_exercise_series')
    # ### end Alembic commands ###
