"""empty message

Revision ID: dbf0adcc0254
Revises: 1d2900323488
Create Date: 2024-11-02 01:00:07.465013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbf0adcc0254'
down_revision = '1d2900323488'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.drop_constraint('exercises_name_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.create_unique_constraint('exercises_name_key', ['name'])

    # ### end Alembic commands ###
